---
title: "Shiny Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(p8105.datasets)
library(plotly)
library(viridis)
library(shiny)
```

```{r}
data("nyc_airbnb")

nyc_airbnb = 
  nyc_airbnb |> 
  mutate(stars = review_scores_location / 2) |> 
  rename(borough = neighbourhood_group) |> 
  select(borough, neighbourhood, stars, price, room_type,
         lat,long) |> 
  drop_na(stars)

```

Column {.sidebar}
-----------------------------------------------------------------------

```{r}
borough_choices = 
  nyc_airbnb |> 
  distinct(borough) |> 
  pull(borough)


selectInput(
  inputId = "borough_choice",
  label = h3("Select Borough"),
  choices = borough_choices,
  selected = "Manhattan"
)
```

```{r}
sliderInput(
  inputId = "price_range",
  label = h3("Select Price Range"),
  min = 100,
  max = 1000,
  value = c(100,400)
)
```



Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
renderPrint(
  input[["borough_choice"]]
)
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
renderPrint(
  input[["price_range"]]
)
```

### Chart C

```{r}

```

